version: "3.3"

services:
  geomaps-db:
    image: postgis/postgis
    container_name: geomaps-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /var/lib/postgresql

  # network_mode: host will point localhost to the local machine
  nginx:
    image: nginx:latest
    container_name: gmnginx
    network_mode: host
    ports:
      - "80:80"
    volumes:
      - ${PWD}/dev.conf:/etc/nginx/conf.d/default.conf:ro

  pgadmin:
    image: dpage/pgadmin4
    container_name: gmpgadmin4
    environment:
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:5050"